# Generated by Django 6.0.2 on 2026-02-17 13:43

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_fname', models.CharField(max_length=255, verbose_name='First Name')),
                ('user_lname', models.CharField(max_length=255, verbose_name='Last Name')),
                ('user_email', models.EmailField(max_length=255, verbose_name='Email')),
                ('user_position', models.CharField(max_length=11, verbose_name='Position')),
                ('pub_date', models.DateTimeField(default=datetime.datetime(2026, 2, 17, 13, 43, 44, 484913, tzinfo=datetime.timezone.utc), verbose_name='Public Date')),
            ],
        ),
    ]
